### PR TITLE
Make compatible with ember-simple-auth v1.1.0-beta.4

### PR DESCRIPTION
**Pull request by bttf**
Small changes; tested and works with ember-simple-auth v1.1.0-beta.4

### CODE REVIEW

**Comment by jamesdixon** [comment]
Thanks, @bttf. I'll get this merged here shortly

**Comment by bttf** [comment]
Thanks,

I also made one more small change - instead of using the native `Promise` object I switched it to use `Ember.RSVP.Promise` which I think makes more sense and allows for better use of promises

(I ran into the issue when trying to call `.finally()` on a promise returned by the firebase authenticator, which doesn't work with native `Promise`)

**Comment by jamesdixon** [comment]
@bttf merged this in. Let me know if you'd be interested in being added as a maintainer. I no longer use firebase, so I haven't done anything with this addon. It could surely use an update on many fronts.

**Comment by bttf** [comment]
@jamesdixon Sure, I only use firebase every now and then but would be glad to help out

**Comment by jamesdixon** [comment]
Great! Just added you as a collaborator!

**Pull request merged**
